"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/AsyncState";
import { useAuth } from "@/hooks/useAuth";
import { getBloodRequest, listAdminRequests, listRequestEvents } from "@/lib/bloodRequests";
import { db } from "@/lib/firebase";
import { collection, getDocs, query, where } from "firebase/firestore";
import type { BloodRequest } from "@/types/domain";

const readable = (value: string) => value.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase());
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${value === "emergency" ? "bg-red-50 text-danger" : value === "approved" ? "bg-green-50 text-success" : "bg-amber-50 text-warning"}`}>{readable(value)}</span>; }

export function AdminRequestQueue() {
  const [requests, setRequests] = useState<BloodRequest[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [urgency, setUrgency] = useState("");
  useEffect(() => { listAdminRequests().then(setRequests).catch(() => setError("We could not load the request queue.")).finally(() => setLoading(false)); }, []);
  const filtered = requests.filter((item) => !urgency || item.urgency === urgency);
  const counts: Array<[string, number]> = ["submitted", "under_review", "approved", "rejected", "fulfilled"].map((status) => [status, requests.filter((item) => item.status === status).length]);
  if (loading) return <LoadingState title="Loading request queue" />; if (error) return <ErrorState description={error} />;
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-medical">Administration</p><h1 className="mt-3 text-4xl font-semibold text-foreground">Request operations</h1><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{counts.map(([status, count]) => <div key={status} className="rounded-[1rem] border border-border bg-surface p-5"><p className="text-xs uppercase tracking-[0.12em] text-foreground-subtle">{readable(status)}</p><p className="mt-2 text-2xl font-semibold text-primary">{count}</p></div>)}</div><div className="mt-8 flex gap-3"><select value={urgency} onChange={(event) => setUrgency(event.target.value)} className="h-11 rounded-lg border border-border-strong bg-surface px-3 text-sm"><option value="">All urgency</option><option value="emergency">Emergency</option><option value="urgent">Urgent</option><option value="routine">Routine</option></select></div>{filtered.length === 0 ? <div className="mt-5"><EmptyState title="No requests in the queue" description="Operational requests will appear here when hospitals submit them." /></div> : <div className="mt-5 overflow-x-auto rounded-[1rem] border border-border bg-surface"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border bg-surface-muted text-xs uppercase tracking-[0.12em] text-foreground-subtle"><tr><th className="px-5 py-4">Request</th><th className="px-5 py-4">Hospital</th><th className="px-5 py-4">Requirement</th><th className="px-5 py-4">Urgency</th><th className="px-5 py-4">Status</th></tr></thead><tbody className="divide-y divide-border">{filtered.map((item) => <tr key={item.id} className={item.urgency === "emergency" ? "bg-red-50/40" : ""}><td className="px-5 py-4"><Link href={`/admin/requests/${item.id}`} className="font-semibold text-primary hover:underline">{item.id.slice(0, 8)}</Link></td><td className="px-5 py-4 text-foreground-muted">{item.hospitalId}</td><td className="px-5 py-4">{item.unitsRequested} × {item.bloodGroup} {readable(item.componentType)}</td><td className="px-5 py-4"><Status value={item.urgency} /></td><td className="px-5 py-4"><Status value={item.status} /></td></tr>)}</tbody></table></div>}</main>;
}

export function AdminDashboard() { return <AdminRequestQueue />; }

export function AdminRequestDetail() {
  const params = useParams<{ requestId: string }>(); const router = useRouter(); const { firebaseUser } = useAuth(); const [request, setRequest] = useState<BloodRequest | null>(null); const [events, setEvents] = useState<Record<string, unknown>[]>([]); const [available, setAvailable] = useState<number | null>(null); const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { Promise.all([getBloodRequest(params.requestId), listRequestEvents(params.requestId)]).then(async ([nextRequest, nextEvents]) => { setRequest(nextRequest); setEvents(nextEvents); if (nextRequest) { const snapshot = await getDocs(query(collection(db, "bloodInventory"), where("bloodGroup", "==", nextRequest.bloodGroup))); setAvailable(snapshot.docs.reduce((sum, item) => sum + (item.data().status === "available" && item.data().componentType === nextRequest.componentType && (!nextRequest.rhFactor || item.data().rhFactor === nextRequest.rhFactor) ? Number(item.data().unitsAvailable || 0) : 0), 0)); } }).catch(() => setError("This request could not be loaded.")).finally(() => setLoading(false)); }, [params.requestId]);
  async function decide(action: "approve" | "reject") { if (!firebaseUser || !request) return; if (action === "approve" && available !== null && available < request.unitsRequested) { setError("Approval is blocked because available stock is insufficient."); return; } if (action === "reject" && !reason.trim()) { setError("A rejection reason is required."); return; } setSubmitting(true); setError(""); try { const token = await firebaseUser.getIdToken(); const response = await fetch("/api/admin/requests/decision", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ requestId: request.id, action, reason }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Decision failed."); setMessage(action === "approve" ? "Request approved and stock reserved." : "Request rejected."); setRequest({ ...request, status: action === "approve" ? "approved" : "rejected" }); router.refresh(); } catch (decisionError) { setError(decisionError instanceof Error ? decisionError.message : "The decision could not be completed."); } finally { setSubmitting(false); } }
  if (loading) return <LoadingState title="Loading request review" />; if (error && !request) return <main className="mx-auto max-w-4xl px-5 py-10 sm:px-8"><ErrorState description={error} /></main>; if (!request) return <main className="mx-auto max-w-4xl px-5 py-10 sm:px-8"><EmptyState title="Request not found" /></main>;
  const approvable = ["submitted", "under_review"].includes(request.status);
  return <main className="mx-auto max-w-4xl px-5 py-10 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-medical">Request review</p><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><h1 className="text-4xl font-semibold text-foreground">Review blood request</h1><Status value={request.status} /></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{[["Hospital", request.hospitalId], ["Patient reference", request.patientId || "—"], ["Requirement", `${request.unitsRequested} × ${request.bloodGroup} ${readable(request.componentType)}`], ["Available matching units", available === null ? "Unavailable" : String(available)], ["Urgency", request.urgency], ["Needed by", request.neededBy?.toDate().toLocaleDateString() || "—"]].map(([heading, value]) => <div key={heading} className="rounded-[1rem] border border-border bg-surface p-5"><p className="text-xs uppercase tracking-[0.12em] text-foreground-subtle">{heading}</p><p className="mt-2 font-semibold capitalize text-foreground">{value}</p></div>)}</div><div className={`mt-6 rounded-[1rem] border p-5 ${available !== null && available >= request.unitsRequested ? "border-green-200 bg-green-50" : "border-red-200 bg-red-50"}`}><p className="font-semibold">{available !== null && available >= request.unitsRequested ? "Sufficient stock" : "Insufficient stock"}</p><p className="mt-1 text-sm">{request.unitsRequested} requested · {available ?? 0} available</p></div><section className="mt-8 rounded-[1rem] border border-border bg-surface p-6"><h2 className="font-semibold text-foreground">Decision</h2><label className="mt-4 grid gap-2 text-sm font-medium">Rejection reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} className="rounded-lg border border-border-strong px-3 py-3" placeholder="Required only when rejecting" /></label>{error && <p role="alert" className="mt-3 text-sm text-danger">{error}</p>}{message && <p role="status" className="mt-3 text-sm text-success">{message}</p>}<div className="mt-5 flex flex-wrap gap-3"><button disabled={submitting || !approvable || available === null || available < request.unitsRequested} onClick={() => decide("approve")} className="rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{submitting ? "Processing…" : "Approve and reserve stock"}</button><button disabled={submitting || !approvable} onClick={() => decide("reject")} className="rounded-lg border border-red-200 px-4 py-3 text-sm font-semibold text-danger disabled:opacity-50">Reject request</button></div></section><section className="mt-8 rounded-[1rem] border border-border bg-surface p-6"><h2 className="font-semibold text-foreground">Request timeline</h2><div className="mt-4 space-y-3">{events.map((event) => <p key={String(event.id)} className="text-sm text-foreground-muted">{readable(String(event.eventType))}</p>)}</div></section></main>;
}
